/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jsondeserialize.example;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.ObjectWriter;
import com.fasterxml.jackson.dataformat.csv.CsvMapper;
import com.fasterxml.jackson.dataformat.csv.CsvSchema;

import jsondeserialize.example.objects.Foo;

public class App {

	public static void main(String[] args) {
		Foo.Builder fooBuilder = new Foo.Builder();
		Foo foo = fooBuilder.foosDouble(3.4).foosInt(11).foosString("aString").build();

		// Works fine
		try {
			printJson(foo);
		} catch (JsonProcessingException e) {
			e.printStackTrace();
		}

		// Does not work
		try {
			printCsv(foo);
		} catch (JsonProcessingException e) {
			e.printStackTrace();
		}

		// Also does not work
		try {
			printCsv2(foo);
		} catch (JsonProcessingException e) {
			e.printStackTrace();
		}
	}

	private static void printCsv(Foo foo) throws JsonProcessingException {

		CsvMapper mapper = new CsvMapper();
		CsvSchema schema = mapper.schemaFor(Foo.class).withHeader();
		ObjectWriter writer = mapper.writer(schema);

		String csvData = writer.writeValueAsString(foo);
		System.out.println(csvData);
	}

	private static void printCsv2(Foo foo) throws JsonProcessingException {

		MyCsvMapper mapper = new MyCsvMapper();
		CsvSchema schema = mapper.schemaFor(Foo.class).withHeader();
		ObjectWriter writer = mapper.writer(schema);

		String csvData = writer.writeValueAsString(foo);
		System.out.println(csvData);
	}

	private static void printJson(Foo foo) throws JsonProcessingException {
		ObjectMapper mapper = new ObjectMapper();
		ObjectWriter writer = mapper.writer();

		String json = writer.writeValueAsString(foo);
		System.out.println(json);
	}
}
